import Head from "next/head"
import React from "react"
import AnimationContainer from "../components/AnimationContainer"
import Modal from "../components/Modal"
import { Region } from "../components/styles/Region.styled"
import { ServicesHeroStyled } from "../components/styles/services/ServicesHeroStyled.styled"
import { Stack } from "../components/styles/Stack.styled"
import { Wrapper } from "../components/styles/Wrapper.styled"

const Contact = () => {
	return (
		<>
			<Head>
				<title>Wlastig Analytics - Contact Us</title>
				<meta
					name="Wlastig Analytics - Web Analytics, Advertising and
	Consulting"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ServicesHeroStyled backgroundImg={"./img/pages/hero-contact.png"}>
				<div className="hero-background">
					<Region>
						<Wrapper>
							<div className="hero-content ">
								<Stack stackAlign={"end"}>
									<AnimationContainer>
										<h1>Let&#39;s talk!</h1>
									</AnimationContainer>
								</Stack>
							</div>
						</Wrapper>
					</Region>
				</div>
			</ServicesHeroStyled>
			<Modal></Modal>
		</>
	)
}

export default Contact
